title: Sarah Neeves # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Geography and Environmental Systems Major</strong> University of Maryland, Baltimore County - Class of 2022
  <br><br>

  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
