title: Sarah Neeves # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>B.S. Geography and Environmental Systems</strong> University of Maryland, Baltimore County '22
  <strong>GIScience Certificate</strong> University of Maryland, Baltimore County '22
  <br><br/>
  <br><br/>
  
  





theme: jekyll-theme-minimal
